@LessonThirty_HostAddress = http://localhost:5160

### Get all products
GET {{LessonThirty_HostAddress}}/api/products
Accept: application/json

### Get a product by ID
GET {{LessonThirty_HostAddress}}/api/products/1
Accept: application/json

### Create a product
POST {{LessonThirty_HostAddress}}/api/products
Content-Type: application/json

{
  "name": "Keyboard",
  "price": 49.99
}
